In [324]:
# Import pandas
import pandas as pd

In [325]:
# Create a DataFrame with balance.txt
df = pd.read_csv('balance.txt', delim_whitespace=True)

In [326]:
#calculate mean income values of only particular ethnicity and store value
avg_caucasian_income = df[df.Ethnicity == "Caucasian"].loc[:,"Income"].mean()
avg_asian_income = df[df.Ethnicity == "Asian"].loc[:,"Income"].mean()
avg_african_american_income = df[df.Ethnicity == "African American"].loc[:,"Income"].mean()

#print out average income for each ethnicity
print(f"The average income of a Caucasian person is {avg_caucasian_income}")
print(f"The average income of an Asian person is {avg_asian_income}")
print(f"The average income of an African American person is {avg_african_american_income}")

The average income of a Caucasian person is 44.521944723618084
The average income of an Asian person is 44.18783333333334
The average income of an African American person is 47.68210101010099

In [327]:
#calculate mean of balance of only married and only single people and store value
avg_married_income = df[df.Married == "Yes"].loc[:,"Balance"].mean()
avg_single_income = df[df.Married == "No"].loc[:,"Balance"].mean()

#print out average balance of married and single people
print(f"The average balance of married people in our dataset is {avg_married_income}")
print(f"The average balance of single people in our dataset is {avg_single_income}")

The average balance of married people in our dataset is 13.388473477498913
The average balance of single people in our dataset is 13.493509015134242

In [328]:
#find maximum and minimum value from only income column then store as variables
max_income = df.loc[:, "Income"].max()
min_income = df.loc[:, "Income"].min()

#print out highest and lowest income from dataset
print(f"The highest income in our dataset is {max_income}")
print(f"The lowest income in our dataset is {min_income}")

The highest income in our dataset is 186.634
The lowest income in our dataset is 10.354

In [329]:
#sum all the values from only the card column and store as variable
total_cards = df["Cards"].sum()

#print total cards
print (f"The total number of cards in our dataset is {total_cards}")

The total number of cards in our dataset is 1183

In [330]:
#count number of instances of male and female in the gender column
females = df[df.Gender == "Female"].loc[:,"Gender"].count()
males = df[df.Gender == "Male"].loc[:,"Gender"].count()

#print out how many women and men there are
print(f"There are {females} women and {males} men in the dataset")

There are 207 women and 193 men in the dataset